import type { ArtifactInput } from './contracts.js';
export const examples: ArtifactInput[] = [
 { id: 'release-plan', template: 'list', data: { title: 'Release plan', rows: ['Review the change', 'Run the test suite', 'Inspect all seven templates', 'Package the Even Hub app', 'Connect the hosted relay', 'Verify the glasses display', 'Test scroll and tap', 'Check reconnect recovery', 'Record hardware evidence'] }, answer: 'Your release plan is ready.\n\nScroll to see the remaining steps. Tap to focus on this answer.\n\nNo action runs automatically.', ttlSeconds: 1800 },
 { id: 'day-plan', template: 'schedule', data: { title: 'A focused morning', events: [ { time: '09:00', title: 'Plan the day', location: 'Workspace', tag: 'Focus' }, { time: '09:30', title: 'Build the adapter', location: 'Workbench' }, { time: '10:30', title: 'Take a break', tag: 'Reset' }, { time: '11:00', title: 'Review the changes', location: 'Workspace' }, { time: '11:45', title: 'Test the display' }, { time: '12:15', title: 'Write the handoff' } ] }, answer: 'Three priorities: build, review, and verify. Your schedule stays beside this answer.', ttlSeconds: 1800 },
 { id: 'architecture-image', template: 'image', data: { src: 'architecture', caption: 'Agent → relay → display' }, answer: 'The relay owns the artifact state. Even Hub relays container updates to the glasses.', ttlSeconds: 1800 },
 { id: 'image-board', template: 'image_grid', data: { title: 'Visual primitives', items: [ { src: 'architecture', label: 'System' }, { src: 'waveform', label: 'Signal' }, { src: 'route', label: 'Route' }, { src: 'grid', label: 'Grid' } ] }, answer: 'A four-image board. These are bundled diagram fixtures; the harness never fetches arbitrary image URLs.', ttlSeconds: 1800 },
 { id: 'reading-list', template: 'list_thumbnails', data: { title: 'Things to explore', rows: [ { src: 'architecture', primary: 'System architecture', secondary: 'Follow the data' }, { src: 'waveform', primary: 'Event flow', secondary: 'Input to state' }, { src: 'route', primary: 'Recovery guide', secondary: 'Reconnect safely' }, { src: 'grid', primary: 'Display limits', secondary: '576 × 288' }, { src: 'architecture', primary: 'Template registry', secondary: 'Seven ways to show data' }, { src: 'grid', primary: 'Acceptance tests', secondary: 'Verify the full loop' } ] }, answer: 'Scroll the illustrated list. The renderer keeps the page structure stable while updating its two image tiles.', ttlSeconds: 1800 },
 { id: 'build-card', template: 'card', data: { title: 'Build ready', subtitle: 'Example status', src: 'grid', rows: [ { label: 'CHECK', value: 'Tests and types complete' }, { label: 'NEXT', value: 'Verify on your glasses' }, { label: 'DELIVERY', value: 'Browser preview only' } ] }, answer: 'This is sample status data. Real bridge acceptance appears separately in the delivery inspector.', ttlSeconds: 1800 },
 { id: 'month-view', template: 'calendar', data: { month: '2026-10', marks: [ { day: 8, label: 'Prototype review' }, { day: 15, label: 'Hardware test' } ] }, answer: 'Two milestones for October. Calendar dates are explicit so the artifact is reproducible.', ttlSeconds: 1800 },
];
